require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'TestConnection' do
  config = use_native_modules!

  project 'TestConnection',
    'Dev.Debug' => :debug, # '{Build Configuration name}' => :{debug or release}
    'Debug' => :debug,
    'Dev.Release' => :release,
    'Release' => :release
    
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"])
  )

  target 'TestConnectionTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
  end
end